# Generated by Django 4.2.3 on 2024-01-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0004_itemtransactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_num', models.PositiveBigIntegerField(null=True)),
                ('ifsc', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('upi_id', models.CharField(max_length=255)),
                ('as_of_date', models.DateField(null=True)),
                ('card_type', models.CharField(max_length=255)),
                ('open_balance', models.BigIntegerField(null=True)),
                ('current_balance', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modules_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invoice', models.CharField(default=0, max_length=100, null=True)),
                ('Estimate', models.IntegerField(default=0, null=True)),
                ('Payment_in', models.IntegerField(default=0, null=True)),
                ('sales_order', models.IntegerField(default=0, null=True)),
                ('Delivery_challan', models.IntegerField(default=0, null=True)),
                ('sales_return', models.IntegerField(default=0, null=True)),
                ('Purchase_bills', models.IntegerField(default=0, null=True)),
                ('Payment_out', models.IntegerField(default=0, null=True)),
                ('Purchase_order', models.IntegerField(default=0, null=True)),
                ('Purchase_return', models.IntegerField(default=0, null=True)),
                ('Bank_account', models.IntegerField(default=0, null=True)),
                ('Cash_in_hand', models.IntegerField(default=0, null=True)),
                ('cheques', models.IntegerField(default=0, null=True)),
                ('Loan_account', models.IntegerField(default=0, null=True)),
                ('Upi', models.IntegerField(default=0, null=True)),
                ('update_action', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='New', max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_type', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('openingbalance', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('creditlimit', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('current_date', models.DateField(blank=True, max_length=255, null=True)),
                ('End_date', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalfield1', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalfield2', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalfield3', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='purchasedebit',
            fields=[
                ('pdebitid', models.AutoField(primary_key=True, serialize=False, verbose_name='pdid')),
                ('reference_number', models.TextField(blank=True, max_length=100, null=True)),
                ('debitdate', models.DateField(null=True)),
                ('billno', models.CharField(max_length=150, null=True)),
                ('billdate', models.CharField(max_length=100, null=True)),
                ('supply', models.CharField(max_length=150, null=True)),
                ('subtotal', models.CharField(max_length=100, null=True)),
                ('sgst', models.CharField(max_length=100, null=True)),
                ('cgst', models.CharField(max_length=100, null=True)),
                ('igst', models.CharField(max_length=100, null=True)),
                ('taxamount', models.CharField(max_length=100, null=True)),
                ('grandtotal', models.CharField(max_length=100, null=True)),
                ('adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('balance_amount', models.FloatField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('cheque_no', models.CharField(default='', max_length=255, null=True)),
                ('upi_no', models.CharField(default='', max_length=255, null=True)),
                ('tot_debt_no', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.party')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='item_stock_in_hand',
            new_name='item_min_stock_maintain',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='staff',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_opening_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemTransactionHistory',
        ),
    ]
