# Generated by Django 4.2.3 on 2024-01-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0005_bankmodel_modules_list_party_purchasedebit_unitmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasedebit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('pdebit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasedebit')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DebitnoteTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('debitnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasedebit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
