# Generated by Django 4.2.3 on 2024-01-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0006_parties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parties',
            old_name='pay_recieve',
            new_name='pay_recieve_pay',
        ),
        migrations.AddField(
            model_name='parties',
            name='pay_recieve_receive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details'),
        ),
    ]
