# Generated by Django 4.2.3 on 2024-01-11 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0007_rename_pay_recieve_parties_pay_recieve_pay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_hsn', models.PositiveIntegerField(null=True)),
                ('item_unit', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_taxable', models.CharField(max_length=255)),
                ('item_gst', models.CharField(max_length=255, null=True)),
                ('item_igst', models.CharField(max_length=255, null=True)),
                ('item_sale_price', models.PositiveIntegerField()),
                ('item_current_stock', models.PositiveBigIntegerField(default=0)),
                ('item_purchase_price', models.PositiveBigIntegerField()),
                ('item_stock_in_hand', models.PositiveBigIntegerField(default=0)),
                ('item_at_price', models.PositiveBigIntegerField(default=0)),
                ('item_date', models.DateField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_invoice', models.PositiveBigIntegerField(blank=True, null=True)),
                ('trans_user_name', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('trans_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_current_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_adjusted_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_price', models.PositiveBigIntegerField(default=0)),
                ('trans_status', models.CharField(max_length=255)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('done_by_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('party', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.parties')),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
