# Generated by Django 4.2.3 on 2024-01-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0008_itemmodel_itemunitmodel_itemtransactionmodel_and_more'),
        ('BillSoftwareapp', '0008_purchaseorder_purchaseordertransactionhistory_and_more'),
    ]

    operations = [
    ]
